# Generated by Django 3.2.13 on 2023-11-08 06:19
# Generated by Django 3.2.13 on 2023-11-07 00:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Gas_Station',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('regular_gas_price', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('premium_gas_price', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('diesel_price', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254)),
                ('message', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
