# Generated by Django 3.2.13 on 2023-11-24 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('station_tracker', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='gas_station',
            name='address',
            field=models.CharField(default='UCCS', max_length=100),
        ),
    ]
