# Generated by Django 4.2.3 on 2023-11-15 22:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('station_tracker', '0002_auto_20231115_2139'),
        ('station_tracker', '0002_gas_station_feedback_phone'),
    ]

    operations = [
    ]
