# Generated by Django 4.2.7 on 2023-11-16 03:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('station_tracker', '0002_feedback_phone'),
        ('station_tracker', '0003_merge_20231115_2258'),
    ]

    operations = [
    ]
