# Generated by Django 3.2.13 on 2023-11-22 04:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('location_search', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Gas_Station',
        ),
    ]
