# Generated by Django 3.2.13 on 2023-11-16 00:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('location_search', '0003_gas_station'),
    ]

    operations = [
        migrations.AddField(
            model_name='search',
            name='fuelType',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='search',
            name='searchPref',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
